// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import deepFreeze from 'deep-freeze';
import { ColorTheme } from '../type-defs';
export const DARK_MODE_THEME_ID = 'dark_mode';

export const DARK_MODE_COLOR_THEME: ColorTheme = deepFreeze({
  identifier: DARK_MODE_THEME_ID,
  displayName: 'Dark mode',
  shade: 'dark',
  animation: {
    scale: 1,
  },
  colors: {
    brand: '#23395B',
    white: '#FFFFFF',
    offWhite: '#FFF4F42',
    baseBackground: '#fafcff',
    borderBackground: '#e0e0e0',
    danger: '#d12428',
    success: '#02730f',
    warning: '#FCE118',
    info: '#E4F8FF',
    darkBackground: '#010318',
    lightBackground: '#F4F4F4',
    dark: '#202020',
    altBackground: '#9c9c9c',
    gray: '#8a8a8a',
    gray20: '#545353',
    gray40: '#616161',
    gray70: '#797979',
    transparent: 'transparent',
    opaque: 'rgba(0,0,0,0.1)',
    forestGreen: '#005807',
    gold: '#F2AC1C',
    lightBlue: '#d9e9fc',
    paceBlue: '#CFDEE7',
    yellow: '#fff703',
    clay: '#967D44',
  },
  fontColors: {
    primary: 'gray20',
    brand: 'brand',
    secondary: 'altBackground',
    baseBorder: 'borderBackground',
    alwaysLight: 'white',
    alwaysDark: 'dark',
    error: 'danger',
    light: 'white',
    disabled: 'gray',
    brandAlt: 'white',
    success: 'success',
    yellow: 'yellow',
    clay: 'clay',
    gold: 'gold',
  },
  backgroundColors: {
    primary: 'white',
    baseBackground: 'baseBackground',
    brand: 'brand',
    altBackground: 'gold',
    darkBackground: 'darkBackground',
    alwaysDark: 'dark',
    alwaysLight: 'white',
    error: 'danger',
    onBackground: 'gray',
    surface: 'offWhite',
    brandAlt: 'white',
    clear: 'transparent',
    info: 'info',
    forestGreen: 'forestGreen',
    success: 'success',
    gold: 'gold',
    lightBlue: 'lightBlue',
    paceBlue: 'paceBlue',
    modal: 'opaque',
    clay: 'clay',
  },
});
